#!/bin/bash
# Example ocr-pdf document.pdf deu+eng

# Create and move to tmp directory
echo "Creating tmp directory .ocrtmp"
tmpdir=/tmp/ocrtmp
rm -rf $tmpdir
mkdir -p $tmpdir
cp $1 $tmpdir
cd $tmpdir

# Convert to PNG
echo "Converting PDF to images"
convert -density 300 $1 pages-%03d.png

# OCR
echo "Converting images to text"
for page in pages-*.png ; do
    tesseract -l $2 /home/work/$page ../${page%.png}
    echo $page.txt
done

# Clean the tmp directory
echo "Cleaning up"
cd /home/work
rm -rf $tmpdir
